# Generated by Django 5.0.1 on 2026-02-01 05:42

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(default='Program Studi Sistem Informasi', max_length=100)),
                ('peringkat', models.CharField(max_length=20)),
                ('nomor_sk', models.CharField(max_length=100)),
                ('tanggal_sk', models.DateField()),
                ('masa_berlaku', models.DateField()),
                ('lembaga', models.CharField(default='BAN-PT', max_length=100)),
                ('certificate_file', models.FileField(upload_to='akreditasi/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Akreditasi',
                'ordering': ['-tanggal_sk'],
            },
        ),
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('tahun_lulus', models.IntegerField()),
                ('pekerjaan', models.CharField(blank=True, max_length=200)),
                ('perusahaan', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='alumni/')),
                ('testimoni', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Alumni',
                'ordering': ['-tahun_lulus'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Kategori Dokumen',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nidn', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('kategori', models.CharField(choices=[('tetap', 'Dosen Tetap'), ('luar_biasa', 'Dosen Luar Biasa')], default='tetap', max_length=20)),
                ('photo', models.ImageField(blank=True, upload_to='dosen/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('pendidikan', models.CharField(max_length=200)),
                ('bidang_keahlian', models.CharField(max_length=200)),
                ('scholar_link', models.URLField(blank=True)),
                ('scopus_link', models.URLField(blank=True)),
                ('sinta_link', models.URLField(blank=True)),
                ('bio', ckeditor.fields.RichTextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Dosen',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Foto'), ('video', 'Video')], default='image', max_length=10)),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='JobCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(default='Full Time', max_length=50)),
                ('description', ckeditor.fields.RichTextField()),
                ('requirements', ckeditor.fields.RichTextField()),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('application_deadline', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('link', models.URLField(blank=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Job Career',
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('kategori', models.CharField(choices=[('siakad', 'SIAKAD'), ('vclass', 'V-Class'), ('ojs', 'Open Journal System'), ('laboratorium', 'Laboratorium'), ('lainnya', 'Lainnya')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor.fields.RichTextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Konten Halaman',
            },
        ),
        migrations.CreateModel(
            name='Penelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('jenis', models.CharField(choices=[('penelitian', 'Penelitian'), ('pengabdian', 'Pengabdian Masyarakat')], max_length=20)),
                ('peneliti', models.CharField(help_text='Nama peneliti (pisahkan dengan koma)', max_length=200)),
                ('year', models.IntegerField()),
                ('abstrak', ckeditor.fields.RichTextField()),
                ('file', models.FileField(blank=True, upload_to='penelitian/')),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Penelitian & Pengabdian',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('achievement', models.CharField(max_length=200)),
                ('tingkat', models.CharField(choices=[('internasional', 'Internasional'), ('nasional', 'Nasional'), ('regional', 'Regional'), ('lokal', 'Lokal')], max_length=20)),
                ('year', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('certificate', models.FileField(blank=True, upload_to='prestasi/')),
                ('photo', models.ImageField(blank=True, upload_to='prestasi/photos/')),
                ('date_achieved', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'Prestasi Mahasiswa',
                'ordering': ['-date_achieved'],
            },
        ),
        migrations.CreateModel(
            name='ProspekKeunggulan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', ckeditor.fields.RichTextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon class', max_length=50)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Prospek & Keunggulan',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sambutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sambutan Ketua Program Studi', max_length=200)),
                ('ketua_name', models.CharField(max_length=100)),
                ('ketua_photo', models.ImageField(upload_to='sambutan/')),
                ('jabatan', models.CharField(default='Ketua Program Studi Sistem Informasi', max_length=100)),
                ('content', ckeditor.fields.RichTextField()),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sambutan',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='slides/')),
                ('link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VisiMisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', ckeditor.fields.RichTextField()),
                ('misi', ckeditor.fields.RichTextField()),
                ('tujuan', ckeditor.fields.RichTextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Visi & Misi',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('thumbnail', models.ImageField(blank=True, upload_to='document_thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.documentcategory')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('thumbnail', models.ImageField(upload_to='news/')),
                ('content', ckeditor.fields.RichTextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-published_date'],
            },
        ),
    ]
