# Generated by Django 5.0.1 on 2026-02-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matakuliah'),
    ]

    operations = [
        migrations.AddField(
            model_name='matakuliah',
            name='dosen_pengampu',
            field=models.TextField(blank=True, help_text='Nama-nama dosen pengampu, pisahkan dengan koma'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='materi_perkuliahan',
            field=models.TextField(blank=True, help_text='Ringkasan materi perkuliahan'),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='rps_document',
            field=models.ForeignKey(blank=True, help_text='Pilih dokumen RPS yang sesuai', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mata_kuliah', to='core.document'),
        ),
    ]
