# Generated by Django 5.0.1 on 2026-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_matakuliah_dosen_pengampu_matakuliah_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pimpinan', 'Pimpinan/Prodi'), ('karyawan', 'Karyawan'), ('stakeholder', 'Stakeholder'), ('dosen', 'Dosen/Tenaga Pengajar'), ('alumni', 'Alumni'), ('mahasiswa', 'Mahasiswa/Mahasiswi')], max_length=50)),
                ('lama_bergabung', models.CharField(max_length=50)),
                ('pengetahuan_visi', models.CharField(max_length=50)),
                ('sumber_informasi', models.JSONField()),
                ('frekuensi_sosialisasi', models.CharField(max_length=50)),
                ('tingkat_paham', models.CharField(max_length=50)),
                ('aspek_tercermin', models.CharField(max_length=50)),
                ('bidang_tercermin', models.JSONField()),
                ('dukungan_atmosfer', models.CharField(max_length=50)),
                ('perlu_perbaikan', models.CharField(max_length=50)),
                ('saran_kritik', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BukuPanduan',
            fields=[
            ],
            options={
                'verbose_name': 'Buku Panduan',
                'verbose_name_plural': 'Buku Panduan',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.document',),
        ),
        migrations.AlterField(
            model_name='matakuliah',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8'), (0, 'Mata Kuliah Pilihan')]),
        ),
    ]
