# Generated by Django 5.0.1 on 2026-02-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_surveyresponse_bukupanduan_alter_matakuliah_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyKepuasanLulusan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nama_responden', models.CharField(max_length=255)),
                ('nama_instansi', models.CharField(max_length=255)),
                ('jabatan', models.CharField(max_length=100)),
                ('integritas', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('keahlian_bidang', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('bahasa_inggris', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('penggunaan_it', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('komunikasi', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('kerjasama_tim', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('pengembangan_diri', models.CharField(choices=[('Sangat Baik', 'Sangat Baik'), ('Baik', 'Baik'), ('Cukup', 'Cukup'), ('Kurang', 'Kurang')], max_length=20)),
                ('waktu_tunggu', models.CharField(choices=[('WT < 3', 'WT < 3 bulan'), ('6 <= WT <= 18', '6 ≤ WT ≤ 18 bulan'), ('WT < 18', 'WT < 18 bulan'), ('24 <= WT <= 36', '24 ≤ WT ≤ 36 bulan')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Kepuasan Lulusan',
                'ordering': ['-created_at'],
            },
        ),
    ]
