# Generated by Django 5.0.1 on 2026-02-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_surveykepuasanlulusan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyKurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_responden', models.CharField(max_length=255)),
                ('kategori_responden', models.CharField(choices=[('alumni', 'Alumni'), ('pakar', 'Dewan Pakar'), ('pengguna', 'Pengguna Lulusan'), ('stakeholder', 'Stakeholder')], max_length=20)),
                ('instansi', models.CharField(max_length=255)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('relevansi_kurikulum', models.IntegerField(choices=[(5, 'Sangat Baik'), (4, 'Baik'), (3, 'Cukup'), (2, 'Kurang'), (1, 'Sangat Kurang')], help_text='Sejauh mana kurikulum relevan dengan kebutuhan industri/dunia kerja saat ini?')),
                ('kompetensi_lulusan', models.IntegerField(choices=[(5, 'Sangat Baik'), (4, 'Baik'), (3, 'Cukup'), (2, 'Kurang'), (1, 'Sangat Kurang')], help_text='Bagaimana penilaian Anda terhadap kompetensi lulusan kami?')),
                ('kualitas_pembelajaran', models.IntegerField(choices=[(5, 'Sangat Baik'), (4, 'Baik'), (3, 'Cukup'), (2, 'Kurang'), (1, 'Sangat Kurang')], default=4, help_text='Bagaimana penilaian Anda terhadap kualitas proses pembelajaran?')),
                ('masukan_mata_kuliah', models.TextField(blank=True, help_text='Mata kuliah apa yang perlu ditambah, dikurangi, atau diperbarui?')),
                ('saran_perbaikan', models.TextField(blank=True, help_text='Saran umum untuk perbaikan kurikulum dan program studi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Survey Kurikulum',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='dosen_pengampu_legacy',
            field=models.TextField(blank=True, help_text='Data lama dosen pengampu (text)'),
        ),
        migrations.RemoveField(
            model_name='matakuliah',
            name='dosen_pengampu',
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='dosen_pengampu',
            field=models.ManyToManyField(blank=True, help_text='Pilih dosen pengampu dari data dosen yang ada', related_name='mata_kuliah_diampu', to='core.dosen'),
        ),
    ]
