# Generated by Django 5.0.1 on 2026-02-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_surveykurikulum_matakuliah_dosen_pengampu_legacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveykurikulum',
            name='kompetensi_lulusan',
        ),
        migrations.RemoveField(
            model_name='surveykurikulum',
            name='kualitas_pembelajaran',
        ),
        migrations.RemoveField(
            model_name='surveykurikulum',
            name='masukan_mata_kuliah',
        ),
        migrations.RemoveField(
            model_name='surveykurikulum',
            name='relevansi_kurikulum',
        ),
        migrations.RemoveField(
            model_name='surveykurikulum',
            name='saran_perbaikan',
        ),
        migrations.AddField(
            model_name='surveykurikulum',
            name='responses_data',
            field=models.JSONField(default=dict, help_text='Data spesifik kuesioner berdasarkan instrumen kategori'),
        ),
    ]
