# Generated by Django 5.0.1 on 2026-04-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_surveykurikulum_kompetensi_lulusan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('ruangan', models.CharField(max_length=50)),
                ('kelas', models.CharField(blank=True, help_text='Contoh: SI-1, Reguler A', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen_pengampu', models.ManyToManyField(blank=True, related_name='jadwal_diampu', to='core.dosen')),
                ('mata_kuliah', models.ForeignKey(help_text='Pilih Mata Kuliah', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal', to='core.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Jadwal Kuliah',
                'ordering': ['hari', 'jam_mulai'],
            },
        ),
    ]
