# Generated by Django 5.0.1 on 2026-04-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jadwalkuliah'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalPerkuliahanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='Contoh: Ganjil, Genap, atau 1, 2', max_length=50)),
                ('kode_mk', models.CharField(max_length=30, verbose_name='Kode MK')),
                ('nama_mk', models.CharField(max_length=300, verbose_name='Nama Mata Kuliah')),
                ('sks', models.IntegerField(verbose_name='SKS')),
                ('jadwal', models.CharField(blank=True, help_text='Contoh: Senin 08:00-10:00', max_length=300, verbose_name='Jadwal Perkuliahan')),
                ('ruangan', models.CharField(blank=True, help_text='Contoh: R.Lab1', max_length=100, verbose_name='Ruangan')),
                ('dosen', models.CharField(blank=True, max_length=500, verbose_name='Dosen Pengampu')),
                ('kode_dosen', models.CharField(blank=True, max_length=50, verbose_name='Kode Dosen / NIDN')),
                ('is_active', models.BooleanField(default=True)),
                ('batch_label', models.CharField(blank=True, help_text='Label batch import, contoh: Genap 2025/2026', max_length=100)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Jadwal Perkuliahan Items',
                'ordering': ['semester', 'kode_mk'],
            },
        ),
    ]
