# Generated by Django 5.0.1 on 2026-04-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_dosen_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitian',
            name='tipe_peneliti',
            field=models.CharField(choices=[('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa'), ('participant', 'Participant')], default='dosen', max_length=20),
        ),
    ]
