# Generated by Django 5.0.1 on 2026-04-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_penelitian_tipe_peneliti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='kategori',
            field=models.CharField(choices=[('tetap', 'Dosen Tetap'), ('dtpr', 'Dosen Tetap Penghitung Rasio'), ('luar_biasa', 'Dosen Luar Biasa')], default='tetap', max_length=28),
        ),
    ]
