# Generated by Django 5.0.1 on 2026-04-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_penelitian_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='jenis',
            field=models.CharField(choices=[('penelitian', 'Penelitian (Riset)'), ('pkm', 'PKM (Pengabdian Masyarakat)'), ('publikasi', 'Publikasi Artikel Jurnal'), ('buku', 'Buku (Referensi/Monograf)')], max_length=20),
        ),
    ]
