# Generated by Django 5.0.1 on 2026-04-27 09:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_penelitian_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitian',
            name='abstrak',
            field=ckeditor.fields.RichTextField(verbose_name='Abstrak / Deskripsi'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='file',
            field=models.FileField(blank=True, upload_to='penelitian/', verbose_name='File Dokumen'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='jenis',
            field=models.CharField(choices=[('penelitian', 'Penelitian (Riset)'), ('pkm', 'PKM (Pengabdian Masyarakat)'), ('publikasi', 'Publikasi Artikel Jurnal'), ('buku', 'Buku (Referensi/Monograf)')], max_length=20, verbose_name='Jenis Karya'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='link',
            field=models.URLField(blank=True, max_length=1000, verbose_name='Link Publikasi'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='peneliti',
            field=models.CharField(help_text='Nama peneliti (pisahkan dengan koma)', max_length=200, verbose_name='Nama Peneliti / Penulis'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='tipe_peneliti',
            field=models.CharField(choices=[('dosen', 'Dosen'), ('mahasiswa', 'Mahasiswa'), ('participant', 'Participant')], default='dosen', max_length=20, verbose_name='Kategori Peneliti'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Judul Karya'),
        ),
        migrations.AlterField(
            model_name='penelitian',
            name='year',
            field=models.IntegerField(verbose_name='Tahun'),
        ),
    ]
