# Generated by Django 5.0.1 on 2026-05-01 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_penelitian_abstrak_alter_penelitian_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dosen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='penelitian',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penelitian_owned', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Data'),
        ),
    ]
