# Generated by Django 5.0.1 on 2026-05-06 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_dosen_user_penelitian_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Kategori Berkas',
            },
        ),
        migrations.CreateModel(
            name='RepositoryBerkas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_berkas', models.CharField(max_length=255)),
                ('no_berkas', models.CharField(blank=True, max_length=100, null=True)),
                ('perihal', models.TextField()),
                ('tahun', models.IntegerField()),
                ('file', models.FileField(upload_to='repository_berkas/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='berkas', to='core.kategoriberkas')),
            ],
            options={
                'verbose_name_plural': 'Repository Berkas',
                'ordering': ['-tahun', '-created_at'],
            },
        ),
    ]
