# Generated by Django 4.2 on 2026-05-08 15:40

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judulproposalskripsi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='judulproposalskripsi',
            name='thn_akademik',
            field=models.CharField(max_length=50, verbose_name='Tahun Akademik'),
        ),
        migrations.AlterField(
            model_name='kerjapraktekmagang',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='kerjapraktekmagang',
            name='instansi_alamat',
            field=models.TextField(verbose_name='Alamat Instansi'),
        ),
        migrations.AlterField(
            model_name='kerjapraktekmagang',
            name='instansi_nama',
            field=models.CharField(max_length=200, verbose_name='Nama Perusahaan/Instansi'),
        ),
        migrations.AlterField(
            model_name='ketuasidang',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ketuasidang',
            name='identitas',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIP/NIK/NIDN'),
        ),
        migrations.AlterField(
            model_name='ketuasidang',
            name='instansi',
            field=models.CharField(default='UNH', help_text='Asal instansi atau jabatan', max_length=100),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Program Studi'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Aktifkan untuk menandai semester berjalan'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='tahun_akademik',
            field=models.CharField(default=core.models.get_current_tahun_akademik, help_text='Contoh: 2023/2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_proposal', to='core.ketuasidang', verbose_name='Ketua'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_proposal_staf', to='core.staf', verbose_name='Notulis (Tendik)'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='pembimbing_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_proposal_ta', to='core.dosen', verbose_name='Pembimbing Proposal'),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='penguji_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_utama_proposal', to='core.dosen', verbose_name='Penguji Utama'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_sidang', to='core.ketuasidang', verbose_name='Ketua'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_sidang_staf', to='core.staf', verbose_name='Notulis (Tendik)'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='pembimbing_pendamping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_pendamping_sidang', to='core.dosen', verbose_name='Pembimbing Pendamping'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='pembimbing_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_utama_sidang', to='core.dosen', verbose_name='Pembimbing Utama'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='penguji_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_utama_sidang', to='core.dosen', verbose_name='Penguji Utama'),
        ),
        migrations.AlterField(
            model_name='staf',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='staf',
            name='nip',
            field=models.CharField(blank=True, max_length=50, verbose_name='NIP/NIK'),
        ),
        migrations.AlterField(
            model_name='tugasakhir',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
