# Generated by Django 5.0.1 on 2026-05-01 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_alter_penelitian_abstrak_alter_penelitian_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik', models.CharField(help_text='Contoh: 2023/2024', max_length=20)),
                ('jenis', models.CharField(choices=[('gasal', 'Gasal'), ('genap', 'Genap')], max_length=10)),
                ('is_active', models.BooleanField(default=False, help_text='Aktifkan untuk menandai semester berjalan')),
            ],
            options={
                'verbose_name_plural': 'Data Semester',
                'ordering': ['-tahun_akademik', '-jenis'],
            },
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20, unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswa_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data Mahasiswa',
                'ordering': ['nim'],
            },
        ),
        migrations.CreateModel(
            name='KerjaPraktekMagang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi_nama', models.CharField(max_length=200, verbose_name='Nama Perusahaan/Instansi')),
                ('instansi_alamat', models.TextField(verbose_name='Alamat Instansi')),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField()),
                ('status', models.CharField(choices=[('pengajuan', 'Pengajuan'), ('disetujui', 'Disetujui'), ('berjalan', 'Sedang Berjalan'), ('selesai', 'Selesai'), ('ditolak', 'Ditolak')], default='pengajuan', max_length=20)),
                ('laporan_file', models.FileField(blank=True, null=True, upload_to='layanan_akademik/kp/laporan/')),
                ('keterangan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dosen_pembimbing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bimbingan_kp', to='core.dosen')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kp_magang', to='layanan_akademik.mahasiswa')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layanan_akademik.semester')),
            ],
            options={
                'verbose_name_plural': 'Kerja Praktek & Magang',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TugasAkhir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('status', models.CharField(choices=[('judul', 'Pengajuan Judul'), ('proposal', 'Seminar Proposal'), ('skripsi', 'Sidang Skripsi'), ('lulus', 'Lulus / Selesai')], default='judul', max_length=20)),
                ('abstrak', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas_akhir', to='layanan_akademik.mahasiswa')),
                ('pembimbing_pendamping', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_pendamping_ta', to='core.dosen')),
                ('pembimbing_utama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_utama_ta', to='core.dosen')),
                ('semester_mulai', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='layanan_akademik.semester')),
            ],
            options={
                'verbose_name_plural': 'Tugas Akhir (Proposal & Skripsi)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SidangSkripsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('ruangan', models.CharField(max_length=100)),
                ('laporan_file', models.FileField(blank=True, null=True, upload_to='layanan_akademik/ta/skripsi/')),
                ('berita_acara', models.FileField(blank=True, null=True, upload_to='layanan_akademik/ta/skripsi/berita_acara/')),
                ('hasil', models.CharField(choices=[('pending', 'Belum Sidang'), ('lulus', 'Lulus'), ('revisi', 'Lulus dengan Revisi'), ('gagal', 'Tidak Lulus / Mengulang')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('penguji_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_1_sidang', to='core.dosen')),
                ('penguji_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_2_sidang', to='core.dosen')),
                ('tugas_akhir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sidang_skripsi', to='layanan_akademik.tugasakhir')),
            ],
            options={
                'verbose_name_plural': 'Jadwal Sidang Skripsi',
            },
        ),
        migrations.CreateModel(
            name='SeminarProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('ruangan', models.CharField(max_length=100)),
                ('laporan_file', models.FileField(blank=True, null=True, upload_to='layanan_akademik/ta/proposal/')),
                ('berita_acara', models.FileField(blank=True, null=True, upload_to='layanan_akademik/ta/proposal/berita_acara/')),
                ('hasil', models.CharField(choices=[('pending', 'Belum Seminar'), ('lulus', 'Lulus'), ('revisi', 'Lulus dengan Revisi'), ('gagal', 'Tidak Lulus / Mengulang')], default='pending', max_length=20)),
                ('catatan', models.TextField(blank=True)),
                ('penguji_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_1_proposal', to='core.dosen')),
                ('penguji_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_2_proposal', to='core.dosen')),
                ('tugas_akhir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_proposal', to='layanan_akademik.tugasakhir')),
            ],
            options={
                'verbose_name_plural': 'Jadwal Seminar Proposal',
            },
        ),
    ]
