# Generated by Django 5.0.1 on 2026-05-01 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_penelitian_abstrak_alter_penelitian_file_and_more'),
        ('layanan_akademik', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seminarproposal',
            name='penguji_1',
        ),
        migrations.RemoveField(
            model_name='seminarproposal',
            name='penguji_2',
        ),
        migrations.RemoveField(
            model_name='sidangskripsi',
            name='penguji_1',
        ),
        migrations.RemoveField(
            model_name='sidangskripsi',
            name='penguji_2',
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_proposal', to='core.dosen', verbose_name='Ketua'),
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_proposal', to='core.dosen', verbose_name='Notulis'),
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='pembimbing_proposal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_proposal_ta', to='core.dosen', verbose_name='Pembimbing Proposal'),
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='penguji_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_utama_proposal', to='core.dosen', verbose_name='Penguji Utama'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_sidang', to='core.dosen', verbose_name='Ketua'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_sidang', to='core.dosen', verbose_name='Notulis'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='pembimbing_pendamping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_pendamping_sidang', to='core.dosen', verbose_name='Pembimbing Pendamping'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='pembimbing_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembimbing_utama_sidang', to='core.dosen', verbose_name='Pembimbing Utama'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='penguji_utama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penguji_utama_sidang', to='core.dosen', verbose_name='Penguji Utama'),
        ),
    ]
