# Generated by Django 5.0.1 on 2026-05-01 14:30

import django.db.models.deletion
import layanan_akademik.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_penelitian_abstrak_alter_penelitian_file_and_more'),
        ('layanan_akademik', '0002_remove_seminarproposal_penguji_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(blank=True, max_length=50, verbose_name='NIP/NIK')),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Data Staf (Tendik/Karyawan)',
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='seminarproposal',
            name='ketua',
        ),
        migrations.RemoveField(
            model_name='sidangskripsi',
            name='ketua',
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='ketua_dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_proposal_dosen', to='core.dosen', verbose_name='Ketua (Internal)'),
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='ketua_external',
            field=models.CharField(blank=True, help_text='Isi jika Ketua bukan dari Dosen tetap', max_length=100, null=True, verbose_name='Ketua (Eksternal)'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='ketua_dosen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_sidang_dosen', to='core.dosen', verbose_name='Ketua (Internal)'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='ketua_external',
            field=models.CharField(blank=True, help_text='Isi jika Ketua bukan dari Dosen tetap', max_length=100, null=True, verbose_name='Ketua (Eksternal)'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='jenis',
            field=models.CharField(choices=[('gasal', 'Gasal'), ('genap', 'Genap')], default='gasal', max_length=10),
        ),
        migrations.AlterField(
            model_name='semester',
            name='tahun_akademik',
            field=models.CharField(default=layanan_akademik.models.get_current_tahun_akademik, help_text='Contoh: 2023/2024', max_length=20),
        ),
        migrations.AlterField(
            model_name='seminarproposal',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_proposal_staf', to='layanan_akademik.staf', verbose_name='Notulis (Tendik)'),
        ),
        migrations.AlterField(
            model_name='sidangskripsi',
            name='notulis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notulis_sidang_staf', to='layanan_akademik.staf', verbose_name='Notulis (Tendik)'),
        ),
    ]
