# Generated by Django 5.0.1 on 2026-05-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_akademik', '0003_staf_remove_seminarproposal_ketua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KetuaSidang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('identitas', models.CharField(blank=True, max_length=50, verbose_name='NIP/NIK/NIDN')),
                ('instansi', models.CharField(default='UNH', help_text='Asal instansi atau jabatan', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Data Ketua Sidang/Seminar',
                'ordering': ['nama'],
            },
        ),
        migrations.RemoveField(
            model_name='seminarproposal',
            name='ketua_dosen',
        ),
        migrations.RemoveField(
            model_name='seminarproposal',
            name='ketua_external',
        ),
        migrations.RemoveField(
            model_name='sidangskripsi',
            name='ketua_dosen',
        ),
        migrations.RemoveField(
            model_name='sidangskripsi',
            name='ketua_external',
        ),
        migrations.AddField(
            model_name='seminarproposal',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_proposal', to='layanan_akademik.ketuasidang', verbose_name='Ketua'),
        ),
        migrations.AddField(
            model_name='sidangskripsi',
            name='ketua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ketua_sidang', to='layanan_akademik.ketuasidang', verbose_name='Ketua'),
        ),
    ]
