# Generated by Django 5.0.1 on 2026-05-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_akademik', '0004_ketuasidang_remove_seminarproposal_ketua_dosen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswa',
            name='prodi',
            field=models.CharField(blank=True, max_length=100, verbose_name='Program Studi'),
        ),
    ]
