# Generated by Django 5.0.1 on 2026-05-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layanan_akademik', '0005_mahasiswa_prodi'),
    ]

    operations = [
        migrations.CreateModel(
            name='JudulProposalSkripsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=20)),
                ('nama_mahasiswa', models.CharField(max_length=100)),
                ('program_studi', models.CharField(max_length=100)),
                ('thn_akademik', models.CharField(max_length=50, verbose_name='Tahun Akademik')),
                ('judul_proposal', models.TextField()),
                ('abstrak', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Judul Proposal Skripsi',
                'ordering': ['-created_at'],
            },
        ),
    ]
